apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-creator-reader-global
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager-sa-global-binding
subjects:
  - kind: ServiceAccount
    name: secret-manager-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: secret-creator-reader-global
  apiGroup: rbac.authorization.k8s.io
