name: semver tag ci
on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  tag-from-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect VERSION change
        id: changed
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^vector-config-reloader/VERSION$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Read version
        if: steps.changed.outputs.changed == 'true'
        id: ver
        run: |
          V=$(tr -d ' \n' < vector-config-reloader/VERSION)
          echo "version=$V" >> $GITHUB_OUTPUT

      - name: Create tag if missing
        if: steps.changed.outputs.changed == 'true'
        run: |
          TAG="v${{ steps.ver.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi
